### ISSUE TITLE
Hubris and Embassy

### ISSUE THREAD

**Issue by andar1an** [flosse/rust-os-comparison#24]
Would you consider Hubris and Embassy good additions to this list? 

Both are related to embedded systems

**Comment by andar1an** [comment]
https://github.com/embassy-rs/embassy

https://github.com/oxidecomputer/hubris

**Comment by flosse** [comment]
> Would you consider Hubris and Embassy good additions to this list?

yes of course :smile:

Would you mind to open a PR?

**Comment by andar1an** [comment]
Not at all, just will take a bit to get to, but I will this week.
